name: Super-Linter and Docker Build/Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_EXTENSIONS: .htm,.html,.dockerfile
          DISABLE_LINTERS: MARKDOWN_LINTER,YAML_LINTER

  build-and-push:
    name: Build and Push Docker Image
    needs: super-linter  # Depends on the linter job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Only run on pushes to master

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/kii-github-actions:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/kii-github-actions:${{ github.sha }}